In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

C:\Users\tegar\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\tegar\anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\tegar\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [2]:
data=pd.read_csv('BTC-USD.csv')
data = data.rename(columns={'Date': 'date','Open':'open','High':'high','Low':'low','Close':'close',
                                'Adj Close':'adj_close','Volume':'volume'})

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

# Filter data
start_date = '2015-01-01'
end_date = '2023-12-31'
filtered_data = data[(data['date'] >= start_date) & (data['date'] <= end_date)]

# Prepare variables
X = filtered_data[['open', 'high', 'low', 'volume']]  # Removed 'date'
y = filtered_data['close']

# Split data
train_size = int(len(X) * 0.8)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Train model RandomForest
randomforest_model = RandomForestRegressor()
randomforest_model.fit(X_train, y_train)
randomforest_predictions = randomforest_model.predict(X_test)


In [4]:
randomforest_predictions

array([46459.3110158 , 45100.72156257, 43202.0681641 , 42447.28105473,
       41463.9276954 , 41529.51000021, 40960.03621091, 42155.63800804,
       43622.18859371, 43042.06937506, 42216.66695333, 42983.50847662,
       42992.96140631, 42102.84503924, 41469.75136738, 41441.22972676,
       42114.40449238, 38166.29249987, 35570.86492206, 35630.20777339,
       35053.77306641, 36953.10527371, 37520.59882831, 36075.96976567,
       36848.71894536, 37887.21535166, 37880.06285166, 37979.38933602,
       38237.55609382, 37921.27621101, 36523.03371107, 40346.38339852,
       41218.38453135, 41493.673711  , 42733.69742205, 44636.66101562,
       44422.68828125, 44568.75457043, 42562.21441429, 42127.15468771,
       41569.19316424, 41886.59058618, 42904.06273454, 44353.15425784,
       42535.06125023, 40214.92511719, 39750.20671884, 38962.02531264,
       38787.36914051, 37901.6925392 , 38153.60648441, 36399.67500018,
       38811.45207031, 39303.41566427, 38621.28859381, 41834.32058607,
      

In [5]:
from itertools import product

def create_mask_arrays(k):
    mask = np.array(list(product(range(2), repeat = k)))
    mask = mask[~np.all(mask== 0, axis=1)]
    mask = mask[~np.all(mask== 1, axis=1)]
    return mask

In [6]:
create_mask_arrays(4)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [7]:
from scipy.special import comb
def calculate_weight(mask_row):
    m=no_of_features=len(mask_row)
    z=no_of_masked_feature=np.sum(mask_row)
    
    weight = (m-1) / ( comb(m,z)*z*(m-z))
    return weight

In [8]:
calculate_weight([0,1,1,1])

0.25

In [9]:
mean_ref_array = X.mean()

In [10]:
mean_ref_array

open      1.444312e+04
high      1.478558e+04
low       1.406841e+04
volume    1.701341e+10
dtype: float64

In [11]:
instance_to_explain = X_test.iloc[0:1]
instance_to_explain

open          high           low       volume
2666  46458.851563  47406.546875  45752.464844  42494677905

In [13]:
print("this?:",randomforest_model.predict(instance_to_explain))

this?: [46459.3110158]


In [14]:
X.columns

Index(['open', 'high', 'low', 'volume'], dtype='object')

In [15]:
mask = create_mask_arrays(len(X.columns))
mask


array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 0, 0],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [16]:
S_with_zero = mask*instance_to_explain.values
print(S_with_zero)
print("-000-")
print(instance_to_explain)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 4.24946779e+10]
 [0.00000000e+00 0.00000000e+00 4.57524648e+04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 4.57524648e+04 4.24946779e+10]
 [0.00000000e+00 4.74065469e+04 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.74065469e+04 0.00000000e+00 4.24946779e+10]
 [0.00000000e+00 4.74065469e+04 4.57524648e+04 0.00000000e+00]
 [0.00000000e+00 4.74065469e+04 4.57524648e+04 4.24946779e+10]
 [4.64588516e+04 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.64588516e+04 0.00000000e+00 0.00000000e+00 4.24946779e+10]
 [4.64588516e+04 0.00000000e+00 4.57524648e+04 0.00000000e+00]
 [4.64588516e+04 0.00000000e+00 4.57524648e+04 4.24946779e+10]
 [4.64588516e+04 4.74065469e+04 0.00000000e+00 0.00000000e+00]
 [4.64588516e+04 4.74065469e+04 0.00000000e+00 4.24946779e+10]
 [4.64588516e+04 4.74065469e+04 4.57524648e+04 0.00000000e+00]]
-000-
              open          high           low       volume
2666  46458.851563  47406.546875  45752.464844  424

In [17]:
S_full = (S_with_zero == 0)*mean_ref_array.values + S_with_zero 
print(S_full)

[[1.44431181e+04 1.47855769e+04 1.40684074e+04 4.24946779e+10]
 [1.44431181e+04 1.47855769e+04 4.57524648e+04 1.70134134e+10]
 [1.44431181e+04 1.47855769e+04 4.57524648e+04 4.24946779e+10]
 [1.44431181e+04 4.74065469e+04 1.40684074e+04 1.70134134e+10]
 [1.44431181e+04 4.74065469e+04 1.40684074e+04 4.24946779e+10]
 [1.44431181e+04 4.74065469e+04 4.57524648e+04 1.70134134e+10]
 [1.44431181e+04 4.74065469e+04 4.57524648e+04 4.24946779e+10]
 [4.64588516e+04 1.47855769e+04 1.40684074e+04 1.70134134e+10]
 [4.64588516e+04 1.47855769e+04 1.40684074e+04 4.24946779e+10]
 [4.64588516e+04 1.47855769e+04 4.57524648e+04 1.70134134e+10]
 [4.64588516e+04 1.47855769e+04 4.57524648e+04 4.24946779e+10]
 [4.64588516e+04 4.74065469e+04 1.40684074e+04 1.70134134e+10]
 [4.64588516e+04 4.74065469e+04 1.40684074e+04 4.24946779e+10]
 [4.64588516e+04 4.74065469e+04 4.57524648e+04 1.70134134e+10]]


In [18]:
calculate_weight([0,1,0,0])

0.25

In [19]:
weights = np.apply_along_axis(calculate_weight, 1, mask)
weights

array([0.25 , 0.25 , 0.125, 0.25 , 0.125, 0.125, 0.25 , 0.25 , 0.125,
       0.125, 0.25 , 0.125, 0.25 , 0.25 ])

In [21]:
# Convert Series to NumPy arrays
mean_ref_array_np = mean_ref_array.to_numpy()
instance_to_explain_np = instance_to_explain.to_numpy()

# Reshape the arrays to have the correct shape
mean_ref_array_reshaped = mean_ref_array_np.reshape(1, -1)
instance_to_explain_reshaped = instance_to_explain_np.reshape(1, -1)

# Predict using the trained Random Forest model
mean_ref_prediction = randomforest_model.predict(mean_ref_array_reshaped)
instance_prediction = randomforest_model.predict(instance_to_explain_reshaped)

print("Our mean model predicts", mean_ref_prediction, "and prediction for the instance we want to explain is:", instance_prediction)


Our mean model predicts [14515.61816398] and prediction for the instance we want to explain is: [46459.3110158]


In [23]:

X = mask 
y = randomforest_model.predict(S_full) 
B0 = randomforest_model.predict(mean_ref_array_reshaped)[0]
W = np.diag(weights) 
y = y - B0 
B = np.dot(np.linalg.inv(np.dot(np.dot(X.transpose(),W),X)), np.dot(np.dot(X.transpose(),W),y)) 
print("Our Shapley values are:", B)

Our Shapley values are: [ 7593.44120766 12687.99777846 11071.79329602  -402.50168617]


In [26]:
y

array([   78.26613288, 10463.65259778, 10448.24875992, 11237.51504901,
       11157.59667986, 23167.52820336, 22984.69017604,  5472.24718748,
        5445.62707033, 18700.74893565, 18555.66276379, 21202.29632824,
       21024.96610362, 32429.93789087])

In [24]:
import pandas as pd

# Assuming x is your DataFrame and B is your NumPy array

# Ensure that x remains a DataFrame
if not isinstance(x, pd.DataFrame):
    x = pd.DataFrame(x, columns=['High', 'Low', 'Open', 'Volume'])  # Replace 'column1', 'column2', ... with actual column names

# Get the column names from your DataFrame x
column_names = x.columns.tolist()

# Check if the number of columns in x matches the number of values in B
if len(column_names) != len(B):
    raise ValueError("Number of columns in x does not match the number of values in B")

# Create a DataFrame with values from B and column names from x
shapley_df = pd.DataFrame([B], columns=column_names)

# Print the DataFrame
print(shapley_df)


NameError: name 'x' is not defined

In [25]:
import shap

# Summarize the background data using shap.sample
background_summary = shap.sample(X_test_processed, 100)

# Create the SHAP explainer with the summarized background data
explainer = shap.KernelExplainer(model.predict, background_summary, link="logit", algorithm="linear")

# Compute SHAP values
shap_values = explainer.shap_values(X_test_processed, nsamples=100)


NameError: name 'X_test_processed' is not defined

In [4]:
shap.initjs() 
shap.force_plot(explainer.expected_value, shap_values[0], 
                              instance_to_explain, link="logit")

NameError: name 'shap' is not defined